### ISSUE TITLE
README não ensina a alterar a configuração da forma correta

### ISSUE THREAD

**Issue by cledsupper** [cledsupper/batservice-a20#3]
Re-escrever README de acordo com a nova versão, que é equivalente à do Magisk.

**Comment by lessodon** [comment]
[batservice-a20-bootleg.tar.gz](https://github.com/cledsupper/batservice-a20/files/7654437/batservice-a20-bootleg.tar.gz)

**Comment by cledsupper** [comment]
Problema corrigido no PR #4
